---
title: "Species Diversity across SGD zones"
author: "Danielle Barnas"
date: "10/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)
```

### Load Libraries ###
```{r}

library(tidyverse)
library(here)
library(stats) # lm() and anova()
library(emmeans)
library(agricolae) # HSD.test()
library(ggrepel)

```

### Read in Data ###
```{r}

div <- read_csv(here("Data","Surveys","Species_Diversity.csv"))

# clusters with Seep
cluster <- read_csv(here("Data", "Surveys", "Cluster_metadata.csv"))
turbcluster <- read_csv(here("Data", "Surveys", "Cluster_turb_metadata.csv"))

# clusters with no Seep
cluster_noSeep <- read_csv(here("Data", "Surveys", "Cluster_metadata_noSeep.csv"))
turbcluster_noSeep <- read_csv(here("Data", "Surveys", "Cluster_turb_metadata_noSeep.csv"))

## nutrients, not transformed or scaled
nutrients <- read_csv(here("Data", "Biogeochem", "AugNutrient_Processed_CV.csv"))

```


### CLUSTERS FROM FULL BIOGEOCHEM ###

#### Diversity with Seep
```{r}

### Clean data ###
spcluster <- div %>%
  #filter(Location == "Varari" | Location == "Varari_Maya") %>%  # all Varari surveys
  left_join(cluster) %>% 
  mutate(V_cluster = ifelse(CowTagID %in% c("RockWall_SGD_1", "RockWall_SGD_2", "RockWall_SGD_3"), "High", V_cluster)) %>% # include rockwall surveys, which are assumed to be "High"
  mutate(Location = ifelse(CowTagID %in% c("RockWall_SGD_1", "RockWall_SGD_2", "RockWall_SGD_3"), "Varari", Location)) %>%
  drop_na(V_cluster) # remove sites without a cluster categorization

# as.factor and relevel cluster ID's
spcluster <- spcluster %>%
  mutate(V_cluster = as.factor(V_cluster)) %>%
  mutate(V_cluster = fct_relevel(V_cluster, levels = c("High", "Mid", "Low"))) %>%
  select(CowTagID, ShannonDivSpecies, V_cluster)

```

#### ANOVA
```{r}
### diversity anova model ###

model1 <- aov(data = spcluster, ShannonDivSpecies ~ V_cluster)
anova(model1)
a <- summary(model1)
ap <- a[[1]]$`Pr(>F)` # isolate p value for graphing

# Tukey post-hoc tests
TukeyHSD(model1)

# based on post-hoc p-values, associate significance letters to cluster factors
sigdifDF <- tibble(V_cluster = as_factor(c("High", "Mid", "Low")),
                   sigdif = as.character(c("a", "a", "a")))

# associate significant difference indicator with cluster ID
spcluster <- spcluster %>%
  left_join(sigdifDF)

# gather summary data using emmeans
graphdata1<-as.data.frame(emmeans(model1, ~ V_cluster))
graphdata1<-graphdata1 %>%
  left_join(sigdifDF) # associate significant difference indicator with cluster ID
graphdata1

```

#### Plotting
```{r, fig.height=7, fig.width=6}
## create palette
V_cluster_palette <- c("#d8a7b1", "#e9ddd4", "#67595e") # 1 is rosewater, 2 is dusty rose, 3 is coffee pot

# graph barplot
plot1 <- ggplot(graphdata1,
       aes(x=V_cluster,
           y=emmean,
           fill = V_cluster)) +
           #group=factorV_cluster)) +
  geom_bar(stat="identity",
           position="dodge",
           color = "#67595e",
           size=0.6) + #determines the bar width
  #theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        #panel.background = element_rect(fill = "azure4"),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12)) +
  geom_errorbar(aes(ymax=emmean+SE, ymin=emmean-SE),
                stat="identity",
                position=position_dodge(width=0.9),
                width=0.1) + #adds error bars
  geom_text(aes(label = sigdif),
                vjust = c(-5, -3, -4),
            size = 5) +
  labs(x="Varari Cluster",
       y="Mean Species Diversity",
       fill = "Relative SGD Influence",
       caption = paste("p =", round(x = ap, 3))) + # labels the x and y axes, legend, and caption
  scale_fill_manual(values=V_cluster_palette) #fill colors for the bars

plot1

# graph boxplot
plot1b <- ggplot(spcluster,
       aes(x = V_cluster,
           y = ShannonDivSpecies,
           fill = V_cluster)) +
  geom_boxplot(color = "black") +
  geom_jitter(color = "black", position = position_jitterdodge()) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        #panel.background = element_rect(fill = "azure4"),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12)) +
  labs(x="Varari Cluster",
       y="Species Diversity",
       fill = "Relative SGD Influence",
       caption = paste("p =", round(x = ap, 3))) + # labels the x and y axes, legend, and caption
  scale_fill_manual(values=V_cluster_palette) #fill colors for the bars

plot1b

ggsave(here("Output","Species_vs_Cluster","V_diversity_barplot.pdf"), plot1, height = 6, width = 6, device = "pdf")
ggsave(here("Output","Species_vs_Cluster","V_diversity_boxplot.pdf"), plot1b, height = 6, width = 6, device = "pdf")

```


#### Diversity with no Seep
```{r}

### Clean data ###
spcluster_noSeep <- div %>%
  #filter(Location == "Varari" | Location == "Varari_Maya") %>%  # all Varari surveys
  left_join(cluster_noSeep) %>% 
  mutate(V_cluster = ifelse(CowTagID %in% c("RockWall_SGD_1", "RockWall_SGD_2", "RockWall_SGD_3"), "High", V_cluster)) %>% # include rockwall surveys, which are assumed to be "High"
  mutate(Location = ifelse(CowTagID %in% c("RockWall_SGD_1", "RockWall_SGD_2", "RockWall_SGD_3"), "Varari", Location)) %>%
  drop_na(V_cluster) # remove sites without a cluster categorization

# as.factor and relevel cluster ID's
spcluster_noSeep <- spcluster_noSeep %>%
  mutate(V_cluster = as.factor(V_cluster)) %>%
  mutate(V_cluster = fct_relevel(V_cluster, levels = c("High", "Mid", "Low"))) %>%
  select(CowTagID, ShannonDivSpecies, V_cluster)

```

#### ANOVA
```{r}
### diversity anova model ###

model2 <- aov(data = spcluster_noSeep, ShannonDivSpecies ~ V_cluster)
anova(model2)
b <- summary(model2)
bp <- b[[1]]$`Pr(>F)` # isolate p value for graphing

# Tukey post-hoc tests
TukeyHSD(model2)

# based on post-hoc p-values, associate significance letters to cluster factors
sigdifDF_noSeep <- tibble(V_cluster = as_factor(c("High", "Mid", "Low")),
                   sigdif = as.character(c("ab", "a", "b")))

# associate significant difference indicator with cluster ID
spcluster_noSeep <- spcluster_noSeep %>%
  left_join(sigdifDF)

# gather summary data using emmeans
graphdata2<-as.data.frame(emmeans(model2, ~ V_cluster))
graphdata2<-graphdata2 %>%
  left_join(sigdifDF_noSeep) # associate significant difference indicator with cluster ID
graphdata2

```

#### Plotting
```{r, fig.height=7, fig.width=6}

# graph
plot2 <- ggplot(graphdata2,
       aes(x=V_cluster,
           y=emmean,
           fill = V_cluster)) +
           #group=factorV_cluster)) +
  geom_bar(stat="identity",
           position="dodge",
           color = "#67595e",
           size=0.6) + #determines the bar width
  #theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        #panel.background = element_rect(fill = "azure4"),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12)) +
  geom_errorbar(aes(ymax=emmean+SE, ymin=emmean-SE),
                stat="identity",
                position=position_dodge(width=0.9),
                width=0.1) + #adds error bars
  geom_text(aes(label = sigdif),
                vjust = c(-4, -3, -5),
            size = 5) +
  labs(x="Varari Cluster",
       y="Mean Species Diversity, excluding Seep",
       fill = "Relative SGD Influence",
       caption = paste("p =", round(x = bp, 3))) + # labels the x and y axes, legend, and caption
  scale_fill_manual(values=V_cluster_palette) #fill colors for the bars

plot2

# graph boxplot
plot2b <- ggplot(spcluster,
       aes(x = V_cluster,
           y = ShannonDivSpecies,
           fill = V_cluster)) +
  geom_boxplot(color = "black") +
  geom_jitter(color = "black", position = position_jitterdodge()) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        #panel.background = element_rect(fill = "azure4"),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12)) +
  labs(x="Varari Cluster",
       y="Species Diversity, excluding Seep",
       fill = "Relative SGD Influence",
       caption = paste("p =", round(x = bp, 3))) + # labels the x and y axes, legend, and caption
  scale_fill_manual(values=V_cluster_palette) #fill colors for the bars

plot2b

ggsave(here("Output","Species_vs_Cluster","V_diversity_barplot_noSeep.pdf"), plot2, height = 6, width = 6, device = "pdf")
ggsave(here("Output","Species_vs_Cluster","V_diversity_boxplot_noSeep.pdf"), plot2b, height = 6, width = 6, device = "pdf")

```





## PCA for clustering
```{r}
Full_V <- spcluster %>% 
  right_join(nutrients)
# C_Cluster_data

# extract parameters for the PCA
V_pca_data <-Full_V %>% 
  filter(Location == "Varari") %>% 
  filter(CowTagID !="VSEEP") %>% 
  select(-(CowTagID:adj_CT_depth_cm))

# C_pca_data <-C_Cluster_data %>% 
#   filter(CowTagID !="CSEEP") %>% 
#   select(-(Location:lon),-C_cluster)

# Run the PCA
pca_V <- prcomp(V_pca_data, scale. = TRUE) # , scale. = TRUE, center = TRUE) # data is already scaled and centered
#pca_C <- prcomp(C_pca_data)

# Extract the scores and loadings
PC_scores_V <-as_tibble(pca_V$x[,1:2])
PC_loadings_V<-as_tibble(pca_V$rotation) %>%
  bind_cols(labels = rownames(pca_V$rotation))

# PC_scores_C <-as_tibble(pca_C$x[,1:2])
# PC_loadings_C<-as_tibble(pca_C$rotation) %>%
#   bind_cols(labels = rownames(pca_C$rotation))

# Put it with all the original data
V_pca_data_all <- Full_V %>%
  filter(Location == "Varari") %>% 
  filter(CowTagID !="VSEEP") %>% 
  bind_cols(PC_scores_V)

# C_pca_data_all<-C_Cluster_data %>%
#   filter(CowTagID !="CSEEP") %>% 
#   bind_cols(PC_scores_C)
```

## scores plot
```{r}
p1_V <- V_pca_data_all %>%
  ggplot(aes(x = PC1, 
             y = PC2, 
             fill = V_cluster))+
  geom_point(shape = 21,
             color = "white",
             size = 3) +
  geom_label_repel(aes(label = paste0(CowTagID,"\n",round(ShannonDivSpecies, 2))),
            color = "black",
            fill = "white",
            size = 3) +
  coord_cartesian(xlim = c(-4, 5), ylim = c(-4, 5)) +
  #scale_shape_manual(values = c(22,16))+
  scale_colour_hue(l = 45)+ # l: luminance/lightness 0-100
  scale_fill_hue(l = 45)+ 
  scale_fill_manual(values = V_cluster_palette) +
  ggforce::geom_mark_ellipse(
    aes(fill = V_cluster, label = V_cluster), 
    alpha = .15, show.legend = FALSE,  label.buffer = unit(1, "mm"))+
  theme_bw()+
  theme(legend.position = "none", 
        #panel.background = element_rect(fill = "azure4"),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank()) +
  labs(title = "Varari Scores Plot with Diversity Index Values")

p1_V
```


```{r}
# p1_C<-C_pca_data_all %>%
#   ggplot(aes(x = PC1, 
#              y = PC2, 
#              fill = C_cluster))+
#   geom_point(shape = 21,
#              color = "white",
#              size = 3) +
#   coord_cartesian(xlim = c(-4, 7), ylim = c(-6, 4)) +
#   #scale_shape_manual(values = c(22,16))+
#   scale_colour_hue(l = 45)+ # l: luminance/lightness 0-100
#   scale_fill_hue(l = 45)+ 
#   scale_fill_manual(values = C_cluster_palette) +
#   ggforce::geom_mark_ellipse(
#     aes(fill = C_cluster, label = C_cluster), 
#     alpha = .15, show.legend = FALSE,  label.buffer = unit(1, "mm"))+
#   theme_bw()+
#   theme(legend.position = "none", panel.background = element_rect(fill = "azure4"),
#         panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
#   labs(title = "Cabral Scores Plot")
# 
# p1_V / p1_C # patchwork plot

```

## loadings plot
```{r}
# loadings plot 
p2_V <- PC_loadings_V %>%
  ggplot(aes(x=PC1, 
             y=PC1, 
             label=labels)) + # labels are the parameters
  geom_segment(aes(x = 0,
                   y = 0,
                   xend = PC1*10,
                   yend=PC2*10),
               arrow = arrow(length=unit(0.1,"cm")), 
               color = "grey") +
  annotate("text", 
           x = PC_loadings_V$PC1*10 + 0.1, 
           y = PC_loadings_V$PC2*10+ 0.1,
           label = PC_loadings_V$labels) +
  coord_cartesian(xlim = c(-5, 5), ylim = c(-5, 2.5)) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank()) +
  labs(title = "Varari Loadings")

p2_V
```

```{r}
# p2_C<-PC_loadings_C %>%
#   ggplot(aes(x=PC1, y=PC1, label=labels))+ # labels are the parameters
#     geom_segment(aes(x=0,y=0,xend=PC1*10,yend=PC2*10),
#       arrow=arrow(length=unit(0.1,"cm")), color = "grey")+
#   annotate("text", x = PC_loadings_C$PC1*10+0.1, y = PC_loadings_C$PC2*10+.1,
#            label = PC_loadings_C$labels)+
#   coord_cartesian(xlim = c(-8, 4), ylim = c(-7, 5)) +
#    theme_bw()+
#   theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
#   labs(title = "Cabral Loadings")
```

```{r, eval = F, echo = F}
### Patch PCA plots
VarariPCA<-p1_V+p2_V+ 
  patchwork::plot_annotation("Varari Clusters", 
                             theme = theme(plot.title = element_text(size = rel(1.5), 
                                                                     face = "bold", 
                                                                     hjust = 0.5, 
                                                                     margin = margin(t = 10, b = 20,
                                                                                     unit = "pt"))))

VarariPCA
```

```{r}
# CabralPCA<-p1_C+p2_C+ 
#   patchwork::plot_annotation("Cabral Clusters", 
#                              theme = theme(plot.title = element_text(size = rel(1.5), 
#                                                                      face = "bold", 
#                                                                      hjust = 0.5, 
#                                                                      margin = margin(t = 10, b = 20,
#                                                                                      unit = "pt"))))

#ggsave(plot = VarariPCA, filename = here("Output","SGDZones","Varari","VarariPCA_CV.pdf"), width = 14, height = 6)
#ggsave(plot = CabralPCA, filename = here("Output","SGDZones","Cabral","CabralPCA_CV.pdf"), width = 14, height = 6)

```


