---
title: "Species Richness and % Cover across SGD zones"
author: "Danielle Barnas"
date: "8/29/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)
```

### Load Libraries ###
```{r}

library(tidyverse)
library(here)
library(stats) # lm() and anova()
library(emmeans)
library(agricolae) # HSD.test()

```

### Read in Data ###
```{r}

spcomp <- read_csv(here("Data","Surveys","Species_Composition_2022.csv")) %>% 
  select(-c(Notes, PhotoNum))

# clusters with Seep
cluster <- read_csv(here("Data", "Surveys", "Cluster_metadata.csv"))
turbcluster <- read_csv(here("Data", "Surveys", "Cluster_turb_metadata.csv"))

# clusters with no Seep
cluster_noSeep <- read_csv(here("Data", "Surveys", "Cluster_metadata_noSeep.csv"))
turbcluster_noSeep <- read_csv(here("Data", "Surveys", "Cluster_turb_metadata_noSeep.csv"))

## nutrients, not transformed or scaled
nutrients <- read_csv(here("Data", "Biogeochem", "AugNutrient_Processed_CV.csv"))

```

### CLUSTERS FROM FULL BIOGEOCHEM ###

#### Richness with Seep
```{r}

### Clean data ###
spcluster <- spcomp %>%
  filter(Location == "Varari" | Location == "Varari_Maya") %>%  # all Varari surveys
  left_join(cluster) %>% 
  mutate(V_cluster = ifelse(CowTagID %in% c("RockWall_SGD_1", "RockWall_SGD_2", "RockWall_SGD_3"), "High", V_cluster)) %>% # include rockwall surveys, which are assumed to be "High"
  drop_na(V_cluster) # remove sites without a cluster categorization

# as.factor and relevel cluster ID's
spcluster <- spcluster %>%
  mutate(V_cluster = as.factor(V_cluster)) %>%
  mutate(V_cluster = fct_relevel(V_cluster, levels = c("High", "Mid", "Low")))


### calculate species richness ###
richness <- spcluster %>%
  select(Location, CowTagID, Taxa, V_cluster) %>%
  group_by(Location, CowTagID, V_cluster) %>%
  count(name = 'spR', Taxa) %>%
  mutate(spR = sum(spR)) %>%
  ungroup() %>%
  select(-Taxa) %>%
  distinct()

### write csv
write_csv(richness, here("Data", "Surveys", "Species_Richness.csv"))

```

```{r}
### richness anova model ###

model1 <- aov(data = richness, spR ~ V_cluster)
anova(model1)
a <- summary(model1)
ap <- a[[1]]$`Pr(>F)` # isolate p value for graphing

# Tukey post-hoc tests
TukeyHSD(model1)

```

```{r, fig.dim = c(10, 10)}
# based on post-hoc p-values, associate significance letters to cluster factors
sigdifDF <- tibble(V_cluster = as_factor(c("High", "Mid", "Low")),
                   sigdif = as.character(c("a", "b", "a")))

# associate significant difference indicator with cluster ID
richness <- richness %>%
  left_join(sigdifDF)


### make a graph of those data ###
# gather summary data using emmeans
graphdata1<-as.data.frame(emmeans(model1, ~ V_cluster))
graphdata1<-graphdata1 %>%
  left_join(sigdifDF) # associate significant difference indicator with cluster ID
graphdata1

## create palette
V_cluster_palette <- c("#d8a7b1", "#e9ddd4", "#67595e") # 1 is rosewater, 2 is dusty rose, 3 is coffee pot

# graph
plot1 <- ggplot(graphdata1,
       aes(x=V_cluster,
           y=emmean,
           fill = V_cluster)) +
           #group=factorV_cluster)) +
  geom_bar(stat="identity",
           position="dodge",
           color = "#67595e",
           size=0.6) + #determines the bar width
  #theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        #panel.background = element_rect(fill = "azure4"),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12)) +
  geom_errorbar(aes(ymax=emmean+SE, ymin=emmean-SE),
                stat="identity",
                position=position_dodge(width=0.9),
                width=0.1) + #adds error bars
  geom_text(aes(label = sigdif),
                vjust = c(-4, -3, -4),
            size = 5) +
  labs(x="Varari Cluster",
       y="Mean Species Richness",
       fill = "Relative SGD Influence",
       caption = paste("p =", round(x = ap, 2))) + # labels the x and y axes, legend, and caption
  scale_fill_manual(values=V_cluster_palette) #fill colors for the bars

plot1

ggsave(here("Output","V_richness_barplot.png"), plot1, height = 6, width = 6, device = "png")
ggsave(here("Output","V_richness_barplot.pdf"), plot1, height = 6, width = 6, device = "pdf")
```

#### Richness with no Seep
```{r}

### Clean data ###
spcluster_noSeep <- spcomp %>%
  filter(Location == "Varari" | Location == "Varari_Maya", # all Varari surveys
         CowTagID != "VSEEP") %>% # remove while using noseep data
  left_join(cluster_noSeep) %>% 
  mutate(V_cluster = ifelse(CowTagID %in% c("RockWall_SGD_1", "RockWall_SGD_2", "RockWall_SGD_3"), "High", V_cluster)) %>% # include rockwall surveys, which are assumed to be "High"
  drop_na(V_cluster) # remove sites without a cluster categorization

# as.factor and relevel cluster ID's
spcluster_noSeep <- spcluster_noSeep %>%
  mutate(V_cluster = as.factor(V_cluster)) %>%
  mutate(V_cluster = fct_relevel(V_cluster, levels = c("High", "Mid", "Low")))


### calculate species richness ###
richness <- spcluster_noSeep %>%
  select(Location, CowTagID, Taxa, V_cluster) %>%
  group_by(Location, CowTagID, V_cluster) %>%
  count(name = 'spR', Taxa) %>%
  mutate(spR = sum(spR)) %>%
  ungroup() %>%
  select(-Taxa) %>%
  distinct()

```

```{r}
### richness anova model ###

model2 <- aov(data = richness, spR ~ V_cluster)
anova(model2)
b <- summary(model2)
bp <- b[[1]]$`Pr(>F)`

# Tukey post-hoc tests
TukeyHSD(model2)

```

```{r, fig.dim = c(10, 10)}
# based on post-hoc p-values, associate significance letters to cluster factors
sigdifDF_noSeep <- tibble(V_cluster = as_factor(c("High", "Mid", "Low")),
                   sigdif = as.character(c("ab", "a", "b")))

# associate significant difference indicator with cluster ID
richness <- richness %>%
  left_join(sigdifDF_noSeep)


### make a graph of those data ###
# gather summary data using emmeans
graphdata2<-as.data.frame(emmeans(model2, ~ V_cluster))
graphdata2<-graphdata2 %>%
  left_join(sigdifDF_noSeep) # associate significant difference indicator with cluster ID
graphdata2


# graph
plot2 <- ggplot(graphdata2,
       aes(x=V_cluster,
           y=emmean,
           fill = V_cluster)) +
           #group=factorV_cluster)) +
  geom_bar(stat="identity",
           position="dodge",
           color = "#67595e",
           size=0.6) + #determines the bar width
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        #panel.background = element_rect(fill = "azure4"),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12)) +
  geom_errorbar(aes(ymax=emmean+SE, ymin=emmean-SE),
                stat="identity",
                position=position_dodge(width=0.9),
                width=0.1) + #adds error bars
  geom_text(aes(label = sigdif),
                vjust = c(-6, -5, -8),
            size = 5) +
  labs(x="Varari Cluster, excluding Seep",
       y="Mean Species Richness",
       fill = "Relative SGD Influence",
       caption = paste("p =", round(x = bp, 2))) + # labels the x and y axes, legend, and caption
  scale_fill_manual(values=V_cluster_palette) #fill colors for the bars

plot2

ggsave(here("Output","V_richness_barplot_noSeep.png"), plot2, height = 10, width = 10, device = "png")
ggsave(here("Output","V_richness_barplot_noSeep.pdf"), plot2, height = 10, width = 10, device = "pdf")
```



#### Percent Cover with Seep
```{r}
### Clean data ###
sp_cover <- spcomp %>%
  filter(Location == "Varari") %>%
  group_by(Location, CowTagID) %>% 
  mutate(totalCount = sum(SpeciesCounts),
         percentCover = SpeciesCounts/totalCount * 100) %>% # percent cover
  select(Location, CowTagID, Taxa, percentCover)

sp_cover <- cluster %>% 
  select(CowTagID, V_cluster) %>% 
  right_join(sp_cover) %>% 
    # as.factor and relevel cluster ID's
  mutate(V_cluster = as.factor(V_cluster)) %>%
  mutate(V_cluster = fct_relevel(V_cluster, levels = c("High", "Mid", "Low")))
```

```{r}
### percent cover anova model ###

model3 <- aov(data = sp_cover, percentCover ~ V_cluster)
anova(model3)
c <- summary(model3)
cp <- c[[1]]$`Pr(>F)`

# Tukey post-hoc tests
TukeyHSD(model3)

```

```{r, fig.dim = c(10, 10)}
# associate significant difference indicator with cluster ID
# sp_cover <- sp_cover %>%
#   mutate(sigdif = ifelse(V_cluster == "Mid", "a", "b"))


### make a graph of those data ###
# gather summary data using emmeans
graphdata3<-as.data.frame(emmeans(model3, ~ V_cluster))
# graphdata2<-graphdata2 %>%
#   mutate(sigdif = ifelse(V_cluster == "Mid", "a", "b")) # as above, associate significant difference indicator with cluster ID
graphdata3


# graph
plot3 <- ggplot(graphdata3,
       aes(x=V_cluster,
           y=emmean,
           fill = V_cluster)) +
           #group=factorV_cluster)) +
  geom_bar(stat="identity",
           position="dodge",
           color = "#67595e",
           size=0.6) + #determines the bar width
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        #panel.background = element_rect(fill = "azure4"),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12)) +
  geom_errorbar(aes(ymax=emmean+SE, ymin=emmean-SE),
                stat="identity",
                position=position_dodge(width=0.9),
                width=0.1) + #adds error bars
  # geom_text(aes(label = sigdif),
  #               vjust = c(-14, -6, -8),
  #           size = 5) +
  labs(x="Varari Cluster",
       y="Mean Species % Cover",
       fill = "Relative SGD Influence",
       caption = paste("p =", round(x = cp, 2))) + # labels the x and y axes, legend, and caption
  scale_fill_manual(values=V_cluster_palette) #fill colors for the bars

plot3

ggsave(here("Output","V_percentCover_barplot.png"), plot3, height = 10, width = 10, device = "png")
ggsave(here("Output","V_percentCover_barplot.pdf"), plot3, height = 10, width = 10, device = "pdf")
```


#### Percent Cover with no Seep
```{r}
### Clean data ###
sp_cover_noSeep <- spcomp %>%
  filter(Location == "Varari") %>%
  group_by(Location, CowTagID) %>% 
  mutate(totalCount = sum(SpeciesCounts),
         percentCover = SpeciesCounts/totalCount * 100) %>% # percent cover
  select(Location, CowTagID, Taxa, percentCover)

sp_cover_noSeep <- cluster_noSeep %>% 
  select(CowTagID, V_cluster) %>% 
  right_join(sp_cover_noSeep) %>% 
    # as.factor and relevel cluster ID's
  mutate(V_cluster = as.factor(V_cluster)) %>%
  mutate(V_cluster = fct_relevel(V_cluster, levels = c("High", "Mid", "Low")))
```

```{r}
### percent cover anova model ###

model4 <- aov(data = sp_cover_noSeep, percentCover ~ V_cluster)
anova(model4)
d <- summary(model4)
dp <- d[[1]]$`Pr(>F)`

# Tukey post-hoc tests
TukeyHSD(model4)

```

```{r, fig.dim = c(10, 10)}
# associate significant difference indicator with cluster ID
# sp_cover <- sp_cover %>%
#   mutate(sigdif = ifelse(V_cluster == "Mid", "a", "b"))


### make a graph of those data ###
# gather summary data using emmeans
graphdata4<-as.data.frame(emmeans(model4, ~ V_cluster))
# graphdata2<-graphdata2 %>%
#   mutate(sigdif = ifelse(V_cluster == "Mid", "a", "b")) # as above, associate significant difference indicator with cluster ID
graphdata4


# graph
plot4 <- ggplot(graphdata4,
       aes(x=V_cluster,
           y=emmean,
           fill = V_cluster)) +
           #group=factorV_cluster)) +
  geom_bar(stat="identity",
           position="dodge",
           color = "#67595e",
           size=0.6) + #determines the bar width
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        #panel.background = element_rect(fill = "azure4"),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12)) +
  geom_errorbar(aes(ymax=emmean+SE, ymin=emmean-SE),
                stat="identity",
                position=position_dodge(width=0.9),
                width=0.1) + #adds error bars
  # geom_text(aes(label = sigdif),
  #               vjust = c(-14, -6, -8),
  #           size = 5) +
  labs(x="Varari Cluster, exclusing Seep",
       y="Mean Species % Cover",
       fill = "Relative SGD Influence",
       caption = paste("p =", round(x = dp, 2))) + # labels the x and y axes, legend, and caption
  scale_fill_manual(values=V_cluster_palette) #fill colors for the bars

plot4

ggsave(here("Output","V_percentCover_barplot_noSeep.png"), plot4, height = 10, width = 10, device = "png")
ggsave(here("Output","V_percentCover_barplot_noSeep.pdf"), plot4, height = 10, width = 10, device = "pdf")
```




### CLUSTERS FROM TURBINARIA CLUSTERS ###

Turbinaria Richness with Seep
```{r}
### Clean data ###
spclusterT <- spcomp %>%
  filter(Location == "Varari") %>%
  left_join(turbcluster)
head(spclusterT)

spclusterT <- spclusterT %>%
  mutate(V_cluster_turb = as.factor(V_cluster_turb)) %>%   # as.factor and relevel cluster ID's
  mutate(V_cluster_turb = fct_relevel(V_cluster_turb, levels = c("High", "Mid", "Low")))


### calculate species richness ###
richnessT <- spclusterT %>%
  rename(V_cluster = V_cluster_turb) %>%
  select(Location, CowTagID, Taxa, V_cluster) %>%
  group_by(Location, CowTagID, V_cluster) %>%
  count(name = 'spR', Taxa) %>%
  mutate(spR = sum(spR)) %>%
  ungroup() %>%
  select(-Taxa) %>%
  distinct()
richnessT

```

```{r}
### anova models ###

model5 <- aov(data = richnessT, spR ~ V_cluster)
anova(model5)
e <- summary(model5)
ep <- e[[1]]$`Pr(>F)`

# Tukey post-hoc tests
TukeyHSD(model5)

```

```{r, fig.dim = c(10, 10)}

### make a graph of those data ###
# gather summary data using emmeans
graphdata5<-as.data.frame(emmeans(model5, ~ V_cluster))
# graphdata3<-graphdata3 %>%
#   mutate(sigdif = ifelse(V_cluster == "High", "a", "b")) %>% # 3 gets a, all else gets b
#   mutate(sigdif = ifelse(V_cluster == "Low", "ab", sigdif)) # replace b with ab for 2, all else maintain a or b
graphdata5


# graph
plot5 <- ggplot(graphdata5,
       aes(x=V_cluster,
           y=emmean,
           fill = V_cluster)) +
  geom_bar(stat="identity",
           position="dodge",
           color = "#67595e",
           size=0.6) + #determines the bar width
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        #panel.background = element_rect(fill = "azure4"),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12)) +
  geom_errorbar(aes(ymax=emmean+SE, ymin=emmean-SE),
                stat="identity",
                position=position_dodge(width=0.9),
                width=0.1) + #adds error bars
  # geom_text(aes(label = sigdif),
  #           vjust = c(-2, -3, -5)) +
  labs(x="Varari Cluster",
       y="Species Richness",
       fill = "Relative SGD Influence",
       caption = paste("p =", round(x = ep, 2))) + # labels the x and y axes, legend, and caption
  scale_fill_manual(values=V_cluster_palette) #fill colors for the bars

plot5

ggsave(here("Output","V_turb_richness_barplot.png"), plot5, height = 10, width = 10, device = "png")
ggsave(here("Output","V_turb_ richness_barplot.pdf"), plot5, height = 10, width = 10, device = "pdf")

```

Turbinaria Richness with no Seep
```{r}
### Clean data ###
spclusterT <- spcomp %>%
  filter(Location == "Varari") %>%
  left_join(turbcluster_noSeep)
head(spclusterT)

spclusterT <- spclusterT %>%
  mutate(V_cluster_turb = as.factor(V_cluster_turb)) %>%   # as.factor and relevel cluster ID's
  mutate(V_cluster_turb = fct_relevel(V_cluster_turb, levels = c("High", "Mid", "Low")))


### calculate species richness ###
richnessT <- spclusterT %>%
  rename(V_cluster = V_cluster_turb) %>%
  select(Location, CowTagID, Taxa, V_cluster) %>%
  group_by(Location, CowTagID, V_cluster) %>%
  count(name = 'spR', Taxa) %>%
  mutate(spR = sum(spR)) %>%
  ungroup() %>%
  select(-Taxa) %>%
  distinct()
richnessT

```

```{r}
### anova models ###

model6 <- aov(data = richnessT, spR ~ V_cluster)
anova(model6)
f <- summary(model6)
fp <- f[[1]]$`Pr(>F)`

# Tukey post-hoc tests
TukeyHSD(model6)

```

```{r, fig.dim = c(10, 10)}
### associate significant difference indicator with cluster ID

### make a graph of those data ###
# gather summary data using emmeans
graphdata6<-as.data.frame(emmeans(model6, ~ V_cluster))
# graphdata3<-graphdata3 %>%
#   mutate(sigdif = ifelse(V_cluster == "High", "a", "b")) %>% # 3 gets a, all else gets b
#   mutate(sigdif = ifelse(V_cluster == "Low", "ab", sigdif)) # replace b with ab for 2, all else maintain a or b
graphdata6


# graph
plot6 <- ggplot(graphdata6,
       aes(x=V_cluster,
           y=emmean,
           fill = V_cluster)) +
  geom_bar(stat="identity",
           position="dodge",
           color = "#67595e",
           size=0.6) + #determines the bar width
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        #panel.background = element_rect(fill = "azure4"),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12)) +
  geom_errorbar(aes(ymax=emmean+SE, ymin=emmean-SE),
                stat="identity",
                position=position_dodge(width=0.9),
                width=0.1) + #adds error bars
  # geom_text(aes(label = sigdif),
  #           vjust = c(-2, -3, -5)) +
  labs(x="Varari Cluster",
       y="Species Richness",
       fill = "Relative SGD Influence",
       caption = paste("p =", round(x = fp, 2))) + # labels the x and y axes, legend, and caption
  scale_fill_manual(values=V_cluster_palette) #fill colors for the bars

plot6

ggsave(here("Output","V_turb_richness_barplot_noSeep.png"), plot6, height = 10, width = 10, device = "png")
ggsave(here("Output","V_turb_richness_barplot_noSeep.pdf"), plot6, height = 10, width = 10, device = "pdf")

```



### Richness linear regression ~ Silicate ###
```{r}

### Process and join nutrient data ###
range_param <- spcluster %>% 
  filter(Location == "Varari") %>% 
  select(-c(Salinity:N_percent)) %>% 
  left_join(nutrients)

### calculate species richness ###
richness <- spcluster %>%
  filter(Location == "Varari") %>% 
  select(Location, CowTagID, Taxa, V_cluster) %>%
  group_by(Location, CowTagID, V_cluster) %>%
  count(name = 'spR', Taxa) %>%
  mutate(spR = sum(spR)) %>%
  ungroup() %>%
  select(-Taxa) %>%
  distinct()

### join richness to biogeochem ###
rich_param <- range_param %>% 
  select(-c(Date, Taxa, SpeciesCounts, 
            TA:Phosphate_umolL, NN_umolL:Tyrosine_Like)) %>% 
  left_join(richness) %>% 
  distinct()

```

```{r}
rich_param %>% 
  filter(CowTagID != "VSEEP") %>% 
  pivot_longer(cols = c(Salinity:N_percent), 
               names_to = "Parameters",
               values_to = "Values") %>% 
  ggplot(aes(x = Values,
           y = spR)) +
  geom_point() +
  geom_smooth(method = "lm", color = "black") +
  facet_wrap(~Parameters, scales = "free_x") +
  theme(panel.background = element_rect(fill = "white"))

```

```{r}
### linear regression ###
model10 <- lm(data = rich_param, spR ~ Salinity)
model11 <- lm(data = rich_param, spR ~ Silicate_umolL)
model12 <- lm(data = rich_param, spR ~ del15N * C_N * N_percent)
model13 <- lm(data = rich_param, spR ~ del15N)
model14 <- lm(data = rich_param, spR ~ N_percent)

### summaries ###
summary(model10)
summary(model11)
summary(model12)
summary(model13)
summary(model14)
```



